### ISSUE TITLE
_swigfaiss_avx2.so may not be loaded properly in conda

### ISSUE THREAD

**Issue by matsui528** [facebookresearch/faiss#1711] opened 2021-02-25 16:15 UTC
# Summary

When I install faiss via conda, `IndexPQFastScan` is slower than `IndexPQ`. It seems that AVX2 is not activated properly because `_swigfaiss_avx2.so` is not loaded correctly.

# Platform

OS: Ubuntu 20.04 on AWS EC2. (ami-0e039c7d64008bd84, c5.large)

Faiss version: faiss-cpu 1.7.0 (pytorch/linux-64::faiss-cpu-1.7.0-py3.8_h2a577fa_0_cpu)

Installed from: conda install -c pytorch faiss-cpu

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

I found that `IndexPQFastScan` is slower than `IndexPQ` for faiss 1.7.0 installed from conda. Here is the benchmark code.

```python
import faiss
import numpy as np
import time

np.random.seed(123)
D = 128
N = 1000
X = np.random.random((N, D)).astype(np.float32)
M = 64
nbits = 4

pq = faiss.IndexPQ(D, M, nbits)
pq.train(X)
pq.add(X)

pq_fast = faiss.IndexPQFastScan(D, M, nbits)
pq_fast.train(X)
pq_fast.add(X)

t0 = time.time()
d1, ids1 = pq.search(x=X[:3], k=5)
t1 = time.time()
print(f"pq: {(t1 - t0) * 1000} msec")

t0 = time.time()
d2, ids2 = pq_fast.search(x=X[:3], k=5)
t1 = time.time()
print(f"pq_fast: {(t1 - t0) * 1000} msec")

assert np.allclose(ids1, ids2)
```

The result is:
```console
pq: 0.4680156707763672 msec
pq_fast: 1.6791820526123047 msec
```

After investigating, the cause seems that `_swigfaiss_avx2.so` is not loaded correctly. If I rename `_swigfaiss_avx2.so` to `_swigfaiss.so`, the above code works as expected:

```console
cd ~/anaconda/lib/python3.8/site-packages/faiss/
mv _swigfaiss.so _swigfaiss.so.bk
mv _swigfaiss_avx2.so _swigfaiss.so
```
Then the benchmark results in:
```console
pq: 0.8258819580078125 msec
pq_fast: 0.07104873657226562 msec
```
Here, `IndexPQFastScan` becomes much faster. 

The root cause seems that `swigfaiss.py` is somehow exactly the same as `swigfaiss_avx2.py`.
```console
diff swigfaiss.py swigfaiss_avx2.py     # same
```
If I understand correctly, `swigfaiss_avx2.py` must load `_swigfaiss_avx2.so`. But currently `swigfaiss_avx2.py` is the same as `swigfaiss.py` and loads `_swigfaiss.so`.

**Comment by mdouze** [comment] 2021-02-26 06:11
Thanks for flagging! 
We are hitting this because there is no reliable way of checking performance regressions in Faiss.
This is probably an issue with the name of the swig module.

**Comment by h-vetinari** [comment] 2021-02-26 15:07
The difference between `swigfaiss.py` and `swigfaiss_avx2.py` doesn't need to be large, it just concerns this portion:

```
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _swigfaiss
else:
    import _swigfaiss
```

which should probably have a `_avx2` suffix in the latter case.

**Comment by h-vetinari** [comment] 2021-02-28 19:40
So I have a preliminary working patch that fixes this in https://github.com/conda-forge/faiss-split-feedstock/pull/34, but it leads to an error in the test suite. Also, this pretty much guarantees that AVX2 hasn't worked so far.

```
=================================== FAILURES ===================================
______________________________ Merge.test_remove _______________________________

self = <test_meta_index.Merge testMethod=test_remove>

    def test_remove(self):
        self.do_test_remove(1)
        self.do_test_remove(2)
>       self.do_test_remove(4)

tests/test_meta_index.py:256:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_meta_index.Merge testMethod=test_remove>, index_type = 4

    def do_test_remove(self, index_type):
        k = 16
        quant = faiss.IndexFlatL2(d)
        index = self.make_index_for_merge(quant, index_type, None)

        # trains the quantizer
        index.train(xt)

        if index_type < 4:
            index.add(xb)
        else:
            gen = np.random.RandomState(1234)
            id_list = gen.permutation(nb * 7)[:nb].astype('int64')
            index.add_with_ids(xb, id_list)


        print('ref search ntotal=%d' % index.ntotal)
        Dref, Iref = index.search(xq, k)

        toremove = np.zeros(nq * k, dtype='int64')
        nr = 0
        for i in range(nq):
            for j in range(k):
                # remove all even results (it's ok if there are duplicates
                # in the list of ids)
                if Iref[i, j] % 2 == 0:
                    nr = nr + 1
                    toremove[nr] = Iref[i, j]

        print('nr=', nr)

        idsel = faiss.IDSelectorBatch(
            nr, faiss.swig_ptr(toremove))

        for i in range(nr):
            assert(idsel.is_member(int(toremove[i])))

        nremoved = index.remove_ids(idsel)

        print('nremoved=%d ntotal=%d' % (nremoved, index.ntotal))

        D, I = index.search(xq, k)

        # make sure results are in the same order with even ones removed
        for i in range(nq):
            j2 = 0
            for j in range(k):
                if Iref[i, j] % 2 != 0:
>                   assert I[i, j2] == Iref[i, j]
E                   AssertionError: assert 31141 == 9101

tests/test_meta_index.py:249: AssertionError
----------------------------- Captured stdout call -----------------------------
ref search ntotal=10000
nr= 7987
nremoved=3952 ntotal=6048
ref search ntotal=10000
nr= 7966
nremoved=3877 ntotal=6123
ref search ntotal=10000
nr= 8075
nremoved=4046 ntotal=5954
=========================== short test summary info ============================
FAILED tests/test_meta_index.py::Merge::test_remove - AssertionError: assert ...
============ 1 failed, 377 passed, 2 warnings in 207.16s (0:03:27) =============
```

**Comment by h-vetinari** [comment] 2021-03-01 18:09
One positive at least: that error is (the only and) consistently the same across all [jobs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=283770&view=results) in the CI. OSX only passes because the azure workers don't have AVX2 and hence don't test that.

**Comment by h-vetinari** [comment] 2021-03-16 21:11
This should now have been fixed by #1717 & #1723

**Comment by matsui528** [comment] 2021-03-21 07:41
AVX2 appears to be working well in the nightly package 🎉  The following code has been tested on my local WSL2 (ubuntu 20.04, python 3.7)

### label: main (w/o AVX2)
- install commands: `conda install -c pytorch faiss-cpu`
- package: `pytorch/linux-64::faiss-cpu-1.7.0-py3.7_h2a577fa_0_cpu`
- result:
    ```
    pq: 0.2841949462890625 msec
    pq_fast: 1.1112689971923828 msec
    ```
- AVX2 is not working. `IndexPQFastScan` is slower.

### label: nightly (w/ AVX2)
- install commands: `conda install -c pytorch/label/nightly faiss-cpu`
- package: `pytorch/label/nightly/linux-64::faiss-cpu-1.7.0-py3.7_h2a577fa_56_cpu`
- result:
    ```
    pq: 0.36454200744628906 msec
    pq_fast: 0.06532669067382812 msec
    ```
- AVX2 is working. `IndexPQFastScan` is faster 🎉 


Not sure why `IndexPQ` w/ AVX2 is slower than that w/o AVX2, though.

**Comment by matsui528** [comment] 2021-03-21 07:49
Some other benchmark results (IVFPQ for siftsmall)

### label: main (w/o AVX2)
- `IndexIVFPQFastScan` is **slower** than `IndexIVFPQ` 
![siftsmall_faiss](https://user-images.githubusercontent.com/2842345/111897798-4e01c180-8a65-11eb-8d1a-8dd9d5f0b736.png)

### label: nightly (w/ AVX2)
- `IndexIVFPQFastScan` is **faster** than `IndexIVFPQ` 
![siftsmall_nightly](https://user-images.githubusercontent.com/2842345/111897805-535f0c00-8a65-11eb-88eb-f68a6f4fcf9a.png)

**Comment by mdouze** [comment] 2021-05-10 05:09
@KinglittleQ @h-vetinari do you know why `instruction_set()` is not in sync with the compile options?

**Comment by mdouze** [comment] 2021-05-10 05:12
> 
> Not sure why `IndexPQ` w/ AVX2 is slower than that w/o AVX2, though.

I am worried that the optimization of PQ2 specific routines may be counter productive, 

https://github.com/facebookresearch/faiss/blob/master/faiss/utils/distances.h#L254

**Comment by KinglittleQ** [comment] 2021-05-10 05:47
> @KinglittleQ @h-vetinari do you know why `instruction_set()` is not in sync with the compile options?

The loader will try to load the generic version if the AVX2 version is not available. So although `instruction_set` return `AVX2` but if there was no available prebuilt AVX2 faiss, the users still use
https://github.com/facebookresearch/faiss/blob/7c2d2388a492d65fdda934c7e74ae87acaeed066/faiss/python/loader.py#L27-L39

**Comment by matsui528** [comment] 2021-06-28 02:33
I confirmed that the following latest main package works. Thank you!
```
faiss-cpu          pytorch/linux-64::faiss-cpu-1.7.1-py3.7_h2a577fa_1_cpu
libfaiss           pytorch/linux-64::libfaiss-1.7.1-h2bc3f7f_1_cpu	
```

**Closed** 2021-06-28 02:33 UTC
Labels: install
