### ISSUE TITLE
Does faiss support the compilation of arm mirroring? If it supports the compilation steps, I read the original article that only version 1.4.0 is OK, is that true, but I have to use version 1.6.3, what should I do?

### ISSUE THREAD

**Issue by yuanpengpeng** [facebookresearch/faiss#1564] opened 2020-12-09 13:38 UTC
Does faiss support the compilation of arm mirroring? If it supports the compilation steps, I read the original article that only version 1.4.0 is OK, is that true, but I have to use version 1.6.3, what should I do?

**Comment by mdouze** [comment] 2020-12-09 14:29
duplicate of #1550

**Closed** 2021-01-05 15:53 UTC
Labels: duplicate
