### ISSUE TITLE
Sudden memory usage increase cause ANN search latency spikes

### ISSUE THREAD

**Issue by zhenglaizhang** [facebookresearch/faiss#3020] opened 2023-08-22 16:10 UTC
I build a hnsw index with 3.6m of 128d embedding for online ANN search, and did a ANN search benchmark with random generated embedding data and topk=200 on a 32 cores k8s pod, the latency looks good, however today I found during benchmark with heavy load and runs for long time e.g. 30+ minutes, the memory usage may suddenly increased from 20g to 40g, and the latency increased from 30ms to 10000+ms the latency and it recovers after 1 or 2 minutes. The latency spikes are most likely due to the memory allocation, but this does not like the expected behavior to me. During ANN search, faiss should only need the necessary memory to hold the objects to serve the request, besides that, will it use another big chunk of memory? It's almost 2x of original memory

**Comment by zhenglaizhang** [comment] 2023-08-23 05:40
From https://github.com/facebookresearch/faiss/issues/1326#issuecomment-671559924 I understand below 
>On CPU, Faiss mainly uses the C++ std::vector allocation, so there is nothing special there. It does geometric reallocation so OOM can happen even if the vectors would fit in RAM.

As the index is already loaded, and served well for search traffic for a few minutes, I am wondering why it happens that the memory spikes happen (20g - 40g) and very latency spikes happens 
<img width="1259" alt="image" src="https://github.com/facebookresearch/faiss/assets/1740859/1fcc06cb-3c18-4da3-baa6-a5e78c919b28">
<img width="1316" alt="image" src="https://github.com/facebookresearch/faiss/assets/1740859/d3ab52e9-fe23-4dbe-b672-59d112d990b9">

**Comment by mdouze** [comment] 2023-08-28 05:38
Thanks for this careful monitoring. How do you perform load balancing? Are there at any point more than 32 queries running? We observe bad performance when there are more concurrent threads than computer cores (and sometimes the optimal number of threads is half the number of cores).

**Comment by zhenglaizhang** [comment] 2023-09-15 09:38
@mdouze right, it's because incorrect omp num threads setup. 

More detail in https://github.com/facebookresearch/faiss/issues/3023#issuecomment-1713479674
> finally figured out that the root cause is due to at application startup I used swigfaiss.omp_set_num_threads(8) to set the omp threads, but actually it doesn't take effect, thoundsands of threads are created in the process. After I changed to override omp threads with environment OMP_NUM_THREADS=8 the threads in the process are reduced to ~300, no more memory spikes and latency spikes.

Do you know what's the difference between omp_set_num_threads method and environment OMP_NUM_THREADS?

**Comment by mengdilin** [comment] 2024-07-26 20:06
@zhenglaizhang 
I'm not able to verify the behavior where swigfaiss.omp_set_num_threads(n) does not work. Looking into the (swig definition)[https://fburl.com/code/z3kzu5nw], we directly expose this function from omp library.
If I run the following on my machine, omp's num threads are getting set correctly:

```
import faiss

nthread = 56
faiss.omp_set_num_threads(nthread)
print("max: ", faiss.omp_get_max_threads()) # prints 56 threads
faiss.omp_set_num_threads(1)
print("max: ", faiss.omp_get_max_threads()) # prints 1 thread
```

I suspect the problem is what @mdouze suspected it, that you called this function in 1 thread but the omp code is spawned from a different thread. Environment variables are shared across threads so the problem disappeared once you use `OMP_NUM_THREADS`

I'm going to close the issue since I cannot reproduce the behavior. Feel free to re-open the issue if you think something else is happening

**Closed by mengdilin** 2024-07-26 20:06 UTC
Labels: documentation, Performance
