### ISSUE TITLE
Risk of causing bugs due to inconsistency in interfaces of `AlignedTableTightAlloc`

### ISSUE THREAD

**Issue by GKxxUCAS** [facebookresearch/faiss#3994] opened 2024-10-28 05:27 UTC
In `faiss/utils/AlignedTable.h`, in the class `AlignedTableTightAlloc`, we can see from the function `resize` that the pointer member `ptr` may be set to null. The copy constructor has taken this into consideration and has performed a check `if (numel > 0)` before passing `ptr` to `memcpy` (which was added in [74ee67a](https://github.com/facebookresearch/faiss/tree/74ee67a)). However, the function `clear` does not seem to have realized this.

Maybe a check should also be performed in `clear` before calling `memset`?

**Comment by pankajsingh88** [comment] 2024-10-28 17:40
Thank you submitting the issue!

I've confirmed that calling clear with `numel == 0` causes invalid-null-argument error. 
Can be reproduced via: 
```
  faiss::AlignedTableTightAlloc<int> atta;
  atta.clear();
 ```

**Comment by pankajsingh88** [comment] 2024-10-28 21:59
closing since the fix https://github.com/facebookresearch/faiss/pull/3997 has landed.

**Closed by pankajsingh88** 2024-10-28 21:59 UTC
Labels: bug, Implementation
