### ISSUE TITLE
How to add data to index?

### ISSUE THREAD

**Issue by XiaXuehai** [facebookresearch/faiss#460] opened 2018-05-25 07:17 UTC
I have built the index by the dataset,and stored on dask.But the dataset is changing by adding vector or deleting vectors frequently.

So does I must rebuild the index everytime or just add/delete the vector from the index built before?

**Comment by beauby** [comment] 2018-05-25 09:04
You can use the `add()` and `remove_ids()` methods.

**Comment by XiaXuehai** [comment] 2018-05-25 09:43
@beauby ,THX. Assume that,If I use the IVF10，and delete too many vectors from the database.the clusters built before is not correct.

**Comment by beauby** [comment] 2018-05-25 10:45
As long as the distribution of the vectors in your training set is close to that of your dataset, the clustering should be ok.
Regarding the number of clusters, the right number depends on the structure of your data.

**Comment by XiaXuehai** [comment] 2018-05-29 06:04
@beauby . if I remove ids,how to realign the remained ids?
remove before :I=[[2,3,4,5,]]
remove ID=0
then,I = [[1,2,3,4]]

**Comment by beauby** [comment] 2018-06-04 11:41
Closing as the issue is resolved. Feel free to keep commenting should you need further help.

**Closed by beauby** 2018-06-04 11:41 UTC
Labels: question

**Comment by engmubarak48** [comment] 2019-07-04 13:22
> You can use the `add()` and `remove_ids()` methods.

Why there is no documentation of adding and removing vectors?. For example, if someone saved an index and would like to add or remove vectors. 

If someone knows how to use these methods or has a link to look for plz share with us.

**Comment by gadregayatri** [comment] 2022-06-08 19:37
I have noticed that if I add a vector, say 'z' to already computed index with IVFx, and then  search the same vector 'z' for this updated index, it does not return 'z' to me. I even tried retraining the  index but no luck. Any idea what could I be doing so that the updated index considers newly added vectors too?

**Comment by fkurushin** [comment] 2024-04-27 10:42
@gadregayatri just tried it right now works fine for me. Keep in mind that fails add the new vectors like stack i.e. in the end.
