### ISSUE TITLE
IndexFlatIP excessive cudaMalloc warnings

### ISSUE THREAD

**Issue by pawlick2** [facebookresearch/faiss#220] opened 2017-10-04 18:08 UTC
My application is running into problems trying to use the IndexFlatIP on GPU.   The python code below is what I've been using to test.

```
import faiss
import numpy as np

# # Configurable params
d = 32                  # dimension of vectors
n_index = 15000000      # number of vectors to index
n_search = 2000000      # total number of vectors to search
page_size = 16384       # number of vectors to search at a time
k = 10                  # number of nearest neighbors to retrieve

temp_memory_absolute = 4 * (1024 * 1024 * 1024)  # Bytes, the single digit is basically GB
# temp_memory_fraction = 0.18

print("Run params: (d = %d, n_index = %d, n_search = %d, page_size = %d, k = %d, memory = %0.2fGB)" %
      (d, n_index, n_search, page_size, k, temp_memory_absolute / 1E9))

# # Create the vectors
index_vectors = np.random.random((n_index, d)).astype('float32')
search_vectors = np.random.random((n_search, d)).astype('float32')

# # Build the index on the CPU first
cpuIndex = faiss.IndexFlatIP(d)
cpuIndex.add(index_vectors)

N_gpu = faiss.get_num_gpus()

# # Initialize the resources
print("Gathering the GPU resources")

# # Note: References to resource_vec, device_vec, and gpu_resources must be kept or will result in segmentation fault
resource_vec = faiss.GpuResourcesVector()
device_vec = faiss.IntVector()
gpu_resources = []

for n in range(N_gpu):
    res = faiss.StandardGpuResources()
    res.setTempMemory(temp_memory_absolute)
    # res.setTempMemoryFraction(temp_memory_fraction)
    gpu_resources.append(res)
    resource_vec.push_back(res)
    device_vec.push_back(n)


# # Define the cloner options
co = faiss.GpuMultipleClonerOptions()
co.useFloat16CoarseQuantizer = False
co.useFloat16 = False
co.shard = False

# # Clone the index to all GPU devices
print("Cloning the index")
index = faiss.index_cpu_to_gpu_multiple(resource_vec, device_vec, cpuIndex, co)

# # Split the search vectors into pages (or chunks, if you will) rather than searching all in one shot
D = np.zeros((n_search, k), dtype='float32')
I = np.zeros((n_search, k), dtype='int64')

n_pages = n_search / page_size + min(1, n_search % page_size)

for n in range(n_pages):
    print('Performing search on page %d out of %d' % (n + 1, n_pages))

    # Get the page of vectors to search with
    idx1 = n * page_size
    idx2 = min((n + 1) * page_size, n_search)
    search_vec_page = search_vectors[idx1:idx2, :]

    # Perform the search
    D_page, I_page = index.search(search_vec_page, k)

    # Put the results in their place
    D[idx1:idx2, :] = D_page
    I[idx1:idx2, :] = I_page

```

My application has about 15M vectors with dimension 32 in the index.  I've implemented a chunking approach to the search vectors to avoid doing them all at once.  With this many vectors, the script is able to complete but with every call to index.search(...) it generates the warning  
```
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 3840000000 B, highwater 3840000000 B)
```
The fact that the warning is thrown with every call makes me think I am really hurting performance, but more importantly I am worried that the program will break when the number of vectors in the index goes up even just a little.  I was able to experiment with parameters for the temp memory and chunk size settings until finding a configuration that works without warnings.  This required me to allocate more than 8GB for temp memory which seems like a lot and is a lot more than the 0.18 fraction of memory that you say is a good rule of thumb for most workloads.

When the size of the index goes up to 20M vectors I am unable to find a set of parameters which eliminates the warnings, except when I reduce the number of vectors searched at a time down to 256 which seems very inefficient.  The temp memory in this case was ~5GB.  As the number of index vectors increases from here I am unable to find any memory and chunk size configurations which work.  The first call to index.search ends with the error  
```
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 5120000000 B, highwater 0 B)
Faiss assertion 'err == cudaSuccess' failed in char* faiss::gpu::StackDeviceMemory::Stack::getAlloc(size_t, cudaStream_t) at utils/StackDeviceMemory.cpp:77; details: cudaMalloc error 2 on alloc size 5120000000
Aborted
```

I am working on an NVIDIA Tesla K80 with 8 GPU devices each having almost 12GB of memory (an AWS p2.8xlarge instance).  Even with 20M vectors the size of the index is only 20M * 32 * sizeof(float) ~= 2.5 GB.

Do I really need all the rest of my available memory to be allocated to the temp_memory?
How much temp memory should I nominally need for a flat index with N vectors in it?
Is this the outcome that I should expect for a workload of this size?

This issue seemed similar to issue #66, it looked like you might have pushed some kind of solution to the repo at the end of that discussion but I'm having this problem having built from the most recent copy of the repo.

Alex

**Comment by wickedfoo** [comment] 2017-10-04 19:43
This might be a problem with the index_cpu_to_gpu_multiple.

Can you just create a single GpuIndexFlatIP, and don't call `setTempMemory` or `setTempMemoryFraction` (i.e., just use the defaults), and pass all of the data to add() in one call to that index, and all the data to `search()` in one call? It should handle paging internally, and not require any more temporary memory than what the resources object allocates by default.

Let me know if you see the `cudaMalloc` message with that. When I get a chance I'll try your script and figure out where the allocation is happening (which I think is likely with something in the cloner).

**Comment by wickedfoo** [comment] 2017-10-04 19:51
Do I really need all the rest of my available memory to be allocated to the temp_memory?

The default value should be sufficient almost always; one shouldn't need to tweak the default value unless you needed to use some of the ~18% that gets reserved by default.

How much temp memory should I nominally need for a flat index with N vectors in it?

The default should be ok.

Is this the outcome that I should expect for a workload of this size?

No, likely a bug somewhere, will investigate.

**Comment by wickedfoo** [comment] 2017-10-04 20:10
Ok, I reproduced the problem.

The particular issue here is that the matrix multiplication for this brute-force calculation is rather large, and is only tiled in one dimension, not two. We handle a large query set, but not querying against a large brute-force database. Our minimum tile size is 64, so we require 15000000 * 64 * sizeof(float) = 3.84 GB of memory.

This is something I can fix (to tile in both dimensions, over the query set and over the database set), but in the meantime you can try multi-GPU with sharding, which reduces the size of the per-GPU matrix, or consider a non-brute force index if that meets your needs.

**Comment by wickedfoo** [comment] 2017-10-04 20:11
Or, you could reduce this `64` to `32` or so as a temporary solution:

https://github.com/facebookresearch/faiss/blob/master/gpu/impl/Distance.cu#L45

**Comment by Alex-Pawlicki-Bose** [comment] 2017-10-04 22:20
Thanks a lot for the insight, I won't be able to try all the solutions until tomorrow but I quickly switched sharding on to try that out since this is something I am interested in being able to do.  It's throwing the error
```
Faiss assertion 'index_ivfpq || index_ivfflat' failed in virtual faiss::Index* faiss::gpu::ToGpuClonerMultiple::clone_Index(const faiss::Index*) at GpuAutoTune.cpp:236; details: IndexShards implemented only for IndexIVFFlat or IndexIVFPQ
Aborted
```
I just created a fresh build of the package from the repo so I believe I should be up to date here.
Do I also need to switch the type of index to one of those IVF types or should I be able to do this on the GPUIndexFlatIP?
Also, in your first reply you suggested forgoing the cloner to test out whether a single index has the same problem, is this a dead suggestion in light of your more recent posts are should I still give that a shot?

**Comment by Alex-Pawlicki-Bose** [comment] 2017-10-05 11:59
This morning I ran some tests with the minimum tile size reduced from 64 to 32 as you suggested.  That looks like it bought me back the extra space being taken up by the index.  I was able to push the upper limit on how many index vectors I had up to 27M without it throwing any warnings or failures but not without having to once again fiddle with the temp_memory until finding a value that worked.

**Comment by wickedfoo** [comment] 2017-10-06 17:29
I will fix this some time so you don't need to fiddle with the temp memory, and it will work for very large collections.

IndexFlat at the moment was not really designed to hold this large of a set of vectors, as it is a brute-force computation, so it doesn't handle well the case where you have more than a million vectors or so (as you are effectively performing a matrix multiplication of size (27000000, 32) x (32, 16384) or larger. Each page size of 16384 requires at least 28.3 TFlops of computation, so it will be pretty slow in any case.

**Comment by wickedfoo** [comment] 2017-10-29 22:16
I have a fix for this internally, should be fixed in this repo whenever we do a synchronization.

**Comment by wickedfoo** [comment] 2017-12-06 17:56
This should work now with latest code without having to do anything special.

**Closed by wickedfoo** 2017-12-06 17:56 UTC
Labels: enhancement
