### ISSUE TITLE
[windows] thread hangs forever in sgemm call

### ISSUE THREAD

**Issue by CascadingRadium** [facebookresearch/faiss#3677] opened 2024-07-23 21:12 UTC
# Summary

parallelly training 2 faiss indexes causes a thread to get stuck forever when using cgo

# Platform

OS: Windows 10

Faiss version: 1.7.4 + few commits from our fork https://github.com/facebookresearch/faiss/compare/main...blevesearch:faiss:bleve

Installed from: Self Compile 

Faiss compilation options: -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_C_API=ON -DBUILD_SHARED_LIBS=ON -DFAISS_ENABLE_PYTHON=OFF .

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [X] C++
- [ ] Python

# Reproduction instructions

### Go version

go version 1.22.5

### What did you do?

Call faiss_Index_train API using 2 parallel go routine (using CGO) on windows 10. (multithreaded openBLAS + faiss lib)

### What did you see happen?

Highly Reproducible issue 

We are encountering a highly reproducible issue related to the use of multithreading in OpenBLAS and FAISS.

We build OpenBLAS in multithreaded mode using USE_THREAD=1 to enhance performance. FAISS, which we use for vector search, is built to utilize this multithreaded OpenBLAS. As FAISS is a C++ library, we use a wrapper library called go-faiss that provides cgo bindings.

reference https://github.com/blevesearch/go-faiss/blob/8a80e00275e2ab4b8af601d045e8d4343c2bcb40/index.go#L109

The issue arises with the Train() API in go-faiss, which is used to train a FAISS index by calling faiss_Index_train. When two Go routines simultaneously call the Train() API, one of them never returns and ends up looping indefinitely.

We observe that these two Go routines each spawn multiple Windows threads for their respective OpenBLAS calls within the Train() API. These Windows threads fail to return, leading to an infinite poll on them.

Specifically, when monitoring the number of times sgemm_ is called, we find that in some instances, a call to sgemm_ never returns and hangs indefinitely within sgemm_.

<img width="857" alt="Screenshot 2024-07-24 at 2 33 31 AM" src="https://github.com/user-attachments/assets/7e4f4858-c994-4c20-94fe-c1089e3b28c0">

### What did you expect to see?

The thread should not get stuck

**Comment by mdouze** [comment] 2024-07-24 15:28
This is hard to reproduce and seems to be a bug with OpenBLAS rather than Faiss.

**Comment by abhinavdangeti** [comment] 2024-08-08 17:07
@mdouze you're right, we've confirmation from the folks working on OpenBLAS - https://github.com/OpenMathLib/OpenBLAS/issues/4844 . Believe we can close this one. Cheers.

**Closed** 2024-08-08 18:20 UTC
Labels: unconfirmed-bug, Implementation, Platform
