### ISSUE TITLE
Will you please help me install Faiss on windows ?

### ISSUE THREAD

**Issue by chengerr** [facebookresearch/faiss#650] opened 2018-12-04 02:56 UTC
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment] 2018-12-04 14:56
https://github.com/facebookresearch/faiss/projects/2
We can help you if you want to undertake this.

**Comment by beauby** [comment] 2018-12-04 17:44
Closing, as this is a duplicate of https://github.com/facebookresearch/faiss/issues/43.

**Closed by beauby** 2018-12-04 17:44 UTC
Labels: duplicate
