### ISSUE TITLE
Faiss only run in CPU not GPU

### ISSUE THREAD

**Issue by a2082761** [facebookresearch/faiss#3257] opened 2024-02-19 02:01 UTC
# Summary

I've been having trouble getting faiss running on my gpu (Cuda) for the past few days. I have installed faiss-gpu several times and even tried installing the conda-forge method and cudatoolkit together as below

$ conda install -c conda-forge faiss-gpu
$ conda install -c pytorch/label/nightly -c nvidia faiss-gpu=1.7.4

Since torch.cuda.is_available() returns True in my code, I think pytorch recognizes cuda, but it seems to be running only on the CPU because it cannot find cuda in faiss.

I would really appreciate it if you could tell me how to install faiss-gpu for my environment. 
Additionally, I must install torch, torchvision, and pillow together. pytorch and faiss must be compatible.

thank you in advance!

# Platform

OS: Ubuntu 22.04.3 LTS

Faiss version:  1.7.4

Installed from:   anaconda

Faiss compilation options:  no option

Faiss compilation options:  no option

my local's cudatoolkit version: 11.4.1

cudatoolkit version: 11.3.1 and 11.4.1 (I tried both)

pytorch version : 1.12.1(I installed by conda)

torchvision version: 0.13.1(I installed by conda)

python version: 3.9

Running on:
- [ ] CPU
- [ v] GPU

Interface: 
- [ ] C++
- [ v] Python

# Reproduction instructions

**Comment by mlomeli1** [comment] 2024-02-20 15:58
Duplicate of https://github.com/facebookresearch/faiss/issues/3181#issuecomment-1953730781 (same user as well). Please do not submit the same issue more than once, we have given you some suggestions in the original issue.

**Closed by mlomeli1** 2024-02-20 15:58 UTC
