### ISSUE TITLE
No conda package for faiss-cpu 1.8.0 for osx-64 on pytorch channel

### ISSUE THREAD

**Issue by glemaitre** [facebookresearch/faiss#3373] opened 2024-04-18 10:35 UTC
# Summary

# Platform

OS: MacOS

Faiss version: 1.8.0

Installed from: conda / pytorch channel

Faiss compilation options: ?

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Currently, there is no conda package for osx-64 while it is available for osx-arm64 for the latest version 1.8.0: https://anaconda.org/pytorch/faiss-cpu

Since that there is an MKL issue with the version 1.7.4 package, then 1.7.3 is quite old.

Is there any reason for the package to not be available?

**Comment by algoriddle** [comment] 2024-04-18 15:30
Duplicate of https://github.com/facebookresearch/faiss/issues/3299

While the deps of 1.7.4 were not completely defined, it's possible to install it by explicitly requiring mkl=2021.

conda install -c pytorch faiss-cpu=1.7.4 mkl=2021 blas=1.0=mkl

should work

**Comment by glemaitre** [comment] 2024-04-19 15:39
> conda install -c pytorch faiss-cpu=1.7.4 mkl=2021 blas=1.0=mkl

Yep but this is a fairly old `mkl` that block the version of `transformers` and library that depends on it. So you end up in dependency nightmare ;)

**Comment by glemaitre** [comment] 2024-04-19 17:48
> Yep but this is a fairly old mkl that block the version of transformers and library that depends on it. So you end up in dependency nightmare ;)

Actually it seems that the `conda` solver is also a culprit here.

**Comment by mlomeli1** [comment] 2024-04-24 17:45
Can you create a fresh conda env with the required packages and then install faiss 1.7.4 using  the --no-deps flag when you install faiss @glemaitre so it doesn't try to downgrade mkl?

**Comment by mlomeli1** [comment] 2024-04-25 09:24
@glemaitre can you try to install tranformers and faiss in the same conda install?

**Comment by glemaitre** [comment] 2024-04-25 09:38
> can you try to install tranformers and faiss in the same conda install?

Actually the issue is indeed in the the resolving of `sentence-transformers` dependencies.
So nothing need to be done on this side. It would still be cool to have a package for `osx-64` since this is not a niche architecture :).

**Closed** 2024-04-25 10:45 UTC
Labels: duplicate
