### ISSUE TITLE
AutoTune.cpp and bench_gpu_1bn.py error

### ISSUE THREAD

**Issue by zhaokang0826** [facebookresearch/faiss#263] opened 2017-11-23 10:20 UTC
Hi：
I have update my faiss code today from the git, but two new errors happen:

**1.AutoTune.cpp error**
1.1 python python/demo_auto_tune.py;(after I set keys_to_test = keys_gpu; use_gpu = True)
RuntimeError: Error in virtual void faiss::ParameterSpace::set_index_parameter(faiss::Index*, const string&, double) const at AutoTune.cpp:500: ParameterSpace::set_index_parameter:could not set parameter nprobe

1.2 python benchs/bench_polysemous_1bn.py SIFT1M IMI2x12,PQ16 nprobe=16,max_codes={10000,30000},ht={44..54}
RuntimeError: Error in faiss::Index* faiss::index_factory(int, const char*, faiss::MetricType) at AutoTune.cpp:804: could not parse token "PQ16" in IMI2x12,PQ16

1.3 python benchs/bench_gpu_sift1m.py
RuntimeError: Error in faiss::Index* faiss::index_factory(int, const char*, faiss::MetricType) at AutoTune.cpp:804: could not parse token "PQ64" in IVF4096,PQ64

**2.bench_gpu_1bn.py error**
2.1 python benchs/bench_gpu_1bn.py SIFT1M OPQ8_32,IVF4096,PQ8 -nnn 10 -ngpu 8 -tempmem $[1536*1024*1024] (**multi gpus**)
Faiss assertion 'err__ == cudaSuccess' failed in faiss::gpu::DeviceTensor<T, Dim, InnerContig, IndexT, PtrTraits>::~DeviceTensor() [with T = float; int Dim = 3; bool InnerContig = true; IndexT = int; PtrTraits = faiss::gpu::traits::DefaultPtrTraits] at impl/../utils/DeviceTensor-inl.cuh:61; details: CUDA error 77

2.2 python benchs/bench_gpu_1bn.py SIFT1M OPQ8_32,IVF4096,PQ8 -nnn 10 -ngpu 1 -tempmem $[1536*1024*1024] (**one gpu**)
Faiss assertion 'err__ == cudaSuccess' failed in faiss::gpu::DeviceTensor<T, Dim, InnerContig, IndexT, PtrTraits>::~DeviceTensor() [with T = float; int Dim = 3; bool InnerContig = true; IndexT = int; PtrTraits = faiss::gpu::traits::DefaultPtrTraits] at impl/../utils/DeviceTensor-inl.cuh:61; details: CUDA error 77

Hope to get your response.

**Comment by mdouze** [comment] 2017-11-23 14:46
Hi 
I just pushed a fix for errors 1.1, 1.2, 1.3. 
I could not repro 2.1 and 2.2.

**Comment by zengzh** [comment] 2017-11-24 10:36
Hi @mdouze ,

I had this error information too.

```
Preparing dataset SIFT1000M
sizes: B (1000000000, 128) Q (10000, 128) T (100000000, 128) gt (10000, 1000)
cachefiles:
/tmp/bench_gpu_1bn/preproc_SIFT1000M_OPQ8_32.vectrans
/tmp/bench_gpu_1bn/cent_SIFT1000M_OPQ8_32,IVF262144.npy
/tmp/bench_gpu_1bn/SIFT1000M_OPQ8_32,IVF262144,PQ8.index
preparing resources for 2 GPUs
load /tmp/bench_gpu_1bn/preproc_SIFT1000M_OPQ8_32.vectrans
load centroids /tmp/bench_gpu_1bn/cent_SIFT1000M_OPQ8_32,IVF262144.npy
making an IVFPQ index, m =  8
Training vector codes
  done 83.490 s
IndexShards shard 0 select modulo 2 = 0
  IndexIVFPQ size 0 -> GpuIndexIVFPQ indicesOptions=0 usePrecomputed=1 useFloat16=0 reserveVecs=500000000
Faiss assertion 'err__ == cudaSuccess' failed in faiss::gpu::DeviceTensor<T, Dim, InnerContig, IndexT, PtrTraits>::~DeviceTensor() [with T = float; int Dim = 3; bool InnerContig = true; IndexT = int; PtrTraits = faiss::gpu::traits::DefaultPtrTraits] at impl/../utils/DeviceTensor-inl.cuh:61; details: CUDA error 77
```

Let me know if you need further information to reproduce the error. 

Thanks.

**Comment by zengzh** [comment] 2017-11-27 01:30
update:

This problem can be avoided using `-noptables`, i.e., do not use precomputed tables

**Comment by zhaokang0826** [comment] 2017-11-29 03:12
Hi @mdouze ，
after you fix for errors 1.1, 1.2, 1.3，when I run 1.3，a new error：
1.3 python benchs/bench_gpu_sift1m.py
load data
load GT
============ Exact search
add vectors to index
warmup
benchmark
k=1 0.442 s, R@1 0.9914
k=2 0.466 s, R@1 0.9940
k=4 0.467 s, R@1 0.9940
k=8 0.469 s, R@1 0.9940
k=16 0.471 s, R@1 0.9941
k=32 0.477 s, R@1 0.9914
k=64 0.485 s, R@1 0.9913
k=128 0.503 s, R@1 0.9941
k=256 0.603 s, R@1 0.9914
k=512 0.761 s, R@1 0.9914
k=1024 1.131 s, R@1 0.9914
============ Approximate search
train
WARNING clustering 100000 points to 4096 centroids: please provide at least 159744 training points
Faiss assertion 'err__ == cudaSuccess' failed in faiss::gpu::DeviceTensor<T, Dim, InnerContig, IndexT, PtrTraits>::~DeviceTensor() [with T = float; int Dim = 3; bool InnerContig = true; IndexT = int; PtrTraits = faiss::gpu::traits::DefaultPtrTraits] at impl/../utils/DeviceTensor-inl.cuh:61; details: CUDA error 77
Aborted

Hope to get your help. Thanks

**Comment by zhaokang0826** [comment] 2017-11-29 03:17
Hi @zengzh,
Do you encounter the error when you run the commands of 1.3 ?

**Comment by zengzh** [comment] 2017-11-29 06:26
@zhaokang0826 

Yes, because of the same reason, precomputed tables.
For the moment, you need `co.usePrecomputed = False` to avoid it.

**Closed** 2017-11-29 10:08 UTC
Labels: bug, cant-repro

**Comment by reshu-b7** [comment] 2018-06-28 10:29
Hi @zhaokang0826 , @zengzh 

I have been facing the same issue while running the bench_gpu_1bn.py on SIFT1B dataset. The script is running on 2 NVIDIA-SMI Tesla GPUs with 24 GB memory for each. The tempmem for each is set as per the command below. I have been noticing this error after `index.add()` and once the script tries copying loaded index to GPUs. 

`python bench_gpu_1bn.py SIFT1M IVF16384,PQ64 -nnn 1 -ngpu 2 -tempmem $[2000*2000*2000] -float16 -noptables -altadd`

```
Preparing dataset SIFT1000M
sizes: B (1000000000, 128) Q (10000, 128) T (100000000, 128) gt (10000, 1000)
cachefiles:
None
/mnt/kann/bench_sift100m/cent_SIFT1000M_IVF16384.npy
/mnt/kann/bench_sift100m/SIFT1000M_IVF16384,PQ64.index
preparing resources for 2 GPUs
load centroids /mnt/kann/bench_sift100m/cent_SIFT1000M_IVF16384.npy
making an IVFPQ index, m =  64
Training vector codes
  done 14.878 s
add...
999981056/1000000000 (16043.609 s)   Add time: 16043.609 s
store /mnt/kann/bench_sift100m/SIFT1000M_IVF16384,PQ64.index
CPU index contains 1000000000 vectors, move to GPU
copying loaded index to GPUs
IndexShards shard 0 select modulo 2 = 0
  IndexIVFPQ size 500000000 -> GpuIndexIVFPQ indicesOptions=0 usePrecomputed=0 useFloat16=1 reserveVecs=0
Faiss assertion 'cudaMalloc(p, size) == cudaSuccess' failed in void faiss::gpu::allocMemorySpace(faiss::gpu::MemorySpace, void**, size_t) at utils/MemorySpace.cpp:20; details: Failed to cudaMalloc 2018048 bytes
```

**Comment by wickedfoo** [comment] 2018-07-07 21:16
@reshu-b7 Two things here:

-PQ64 x 500M vectors per GPU is 32 GB of memory. This cannot fit on your GPU, so it is running out of memory part way during the copy for some inverted list (the failled to allocate 2018048 bytes). With 24 GB of memory, PQ16 or PQ32 is more reasonable.
-You are allocating 8 GB of temporary memory. 1 to 2 GB at most should be ok.
