### ISSUE TITLE
Will Faiss appear on PyPI in the light of the recent news?

### ISSUE THREAD

**Issue by Yura52** [facebookresearch/faiss#4030] opened 2024-11-17 10:53 UTC
The PyTorch team will soon stop publishing packages to Conda: https://github.com/pytorch/pytorch/issues/138506

I wonder if the Faiss team is planning something similar. In particular, I wonder if the following technical context can make the PyPI story more accessible for Faiss and its users than before.

(1) NVIDIA now publishes its packages on PyPI, and my understanding is that PyTorch already relies on that.

(2) [uv](https://github.com/astral-sh/uv) is becoming increasingly popular in the Python community, and it provides an easy way to specify custom PyPI index for specific packages in `pyproject.toml`, if, for whatever reason, the default index is not suitable for a given package. For example:

```
# pyproject.toml

[project]
...
dependencies = [
    ...,
    "torch ==2.0.1",
]

[tool.uv.sources]
torch = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true
```

**Comment by junjieqi** [comment] 2024-11-18 00:31
@Yura52 it is definitely on our radar. We also discussed it internally as well. Will keep updated in the community. cc @asadoughi

**Comment by asadoughi** [comment] 2024-11-18 02:07
Closing as duplicate of #3152

**Closed by asadoughi** 2024-11-18 02:07 UTC
Labels: install, feature request
