### ISSUE TITLE
Build fails with 3 errors "has already been defined"

### ISSUE THREAD

**Issue by otaj** [facebookresearch/faiss#1159] opened 2020-03-24 16:38 UTC
# Summary
Hi, it seems, that current version in `master` is not compilable, the GPU compilation failed with following error:

```
gpu/impl/PQScanMultiPassNoPrecomputed.cu(27): error: function "faiss::gpu::isSupportedNoPrecomputedSubDimSize" has already been defined

gpu/impl/PQScanMultiPassNoPrecomputed.cu(51): error: class template "faiss::gpu::LoadCodeDistances" has already been defined

gpu/impl/PQScanMultiPassNoPrecomputed.cu(123): error: function template "faiss::gpu::pqScanNoPrecomputedMultiPass" has already been defined

3 errors detected in the compilation of "/tmp/tmpxft_0007f108_00000000-11_PQScanMultiPassNoPrecomputed.compute_75.cpp1.ii".
make: *** [Makefile:45: gpu/impl/PQScanMultiPassNoPrecomputed.o] Error 1
make: *** Waiting for unfinished jobs....
```

# Platform

OS: Arch Linux
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-pkgversion='Arch Linux 9.3.0-1' --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
gcc version 9.3.0 (Arch Linux 9.3.0-1) 
```
```
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```

Faiss version: `a17a631`

Faiss compilation options: nothing fancy.

# Reproduction instructions

Compiling current master on Linux with GPU should be enough. I am also a maintainer of AUR faiss [package](https://aur.archlinux.org/packages/faiss-cuda-git/)

**Comment by mdouze** [comment] 2020-03-25 08:55
@beauby  maybe a good idea to include GPU Faiss compilation in the CI, even if there is no hardware to run the tests.

**Comment by dvzubarev** [comment] 2020-03-25 16:23
I can confirm those errors:
```
gcc version 9.2.0
Cuda compilation tools, release 10.2, V10.2.89
GPU: GeForce RTX 2080 Ti
./configure --with-cuda-arch="-gencode=arch=compute_75,code=sm_75"
make -j4
```
Except those errors, I also have a lot of warnings:

<details>
  <summary>log</summary>

```
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi32ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi32ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi32ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi32ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi28ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi28ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi28ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi28ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi24ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi24ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi24ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi24ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi20ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi20ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi20ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi20ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi16ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi16ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi16ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi16ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi12ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi12ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi12ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi12ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi10ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi10ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi10ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi10ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi8ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi8ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi8ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi8ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi6ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi6ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi6ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi6ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi4ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi4ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi4ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi4ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi3ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi3ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi3ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi3ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi2ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi2ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi2ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi2ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi1ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi1ELb0EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1EiS5_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesIfLi1ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS5_NS2_IfLi3ELb1EiS4_EENS2_IiLi2ELb1EiS4_EENS2_IT_Li4ELb1EiS4_EE is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi1ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1Ei

```

</details>

**Comment by otaj** [comment] 2020-03-25 16:25
@dvzubarev Oh yeah, I had the same host of warnings, I just thought that posting only errors would be more useful.

**Comment by wickedfoo** [comment] 2020-03-25 16:35
I'm looking into this.

**Comment by wickedfoo** [comment] 2020-03-25 17:27
PQScanMultiPassNoPrecomputed.cu was deleted in the internal FB version but doesn't seem to be deleted in the github version (for us, the internal FB version is the source of truth, not github).

Investigating what other sync issues there may be, but in the meantime, removing PQScanMultiPassNoPrecomputed.cu from your build may fix the issue.

**Comment by wickedfoo** [comment] 2020-03-25 17:33
gpu/impl/PQCodeDistances.cu should have been deleted as well.

**Comment by dvzubarev** [comment] 2020-03-25 17:46
Thx, deleting those two files fixes the errors for me. But warnings are still here, should I worry about these warnings?

**Comment by wickedfoo** [comment] 2020-03-25 17:49
@dvzubarev the other errors in your log are unrelated and have to do with the fact that you are compiling for a Turing architecture GPU:

`ptxas warning : Value of threads per SM for entry _ZN5faiss3gpu15pqCodeDistancesI6__halfLi1ELb1EEEvNS0_6TensorIfLi2ELb1EiNS0_6traits16DefaultPtrTraitsEEEiS6_NS3_IfLi3ELb1EiS5_EENS3_IiLi2ELb1EiS5_EENS3_IT_Li4ELb1Ei`

I'll open up a separate issue on this and see if I can fix it, as we haven't tried compiling Faiss for Turing GPUs yet.

**Comment by otaj** [comment] 2020-03-25 17:51
Thanks too, I am able to build now as well. I modified the AUR package to be able to build, however it would be a lot better, if the files were deleted in this repo.

**Comment by wickedfoo** [comment] 2020-03-25 17:52
I filed a separate issue to look at Turing architecture compilation
https://github.com/facebookresearch/faiss/issues/1161

**Comment by wickedfoo** [comment] 2020-03-25 17:59
I removed the files in question from the repo, clone again and see if it fixes this issue, and I will close it if so.

@dvzubarev I'm looking separately at the Turing architecture build issue.

**Comment by wickedfoo** [comment] 2020-03-25 23:02
@dvzubarev This is not a Turing issue at all, but seems to be a warning added in CUDA 10+. I will fix but should be ok to ignore at the moment, only side effect would be potentially lower performance for GpuIndexIVFPQ in certain configurations.

**Comment by dvzubarev** [comment] 2020-03-26 07:28
Ok, Thank you for looking into this.

**Closed** 2020-03-26 21:58 UTC
Labels: GPU, install

**Comment by zaemyung** [comment] 2020-09-03 10:54
@wickedfoo 
For some reason, both `PQCodeDistances.cu` and `PQScanMultiPassNoPrecomputed.cu` are back in Faiss 1.6.3, causing the same errors. Removing those files resolves the issue.

**Comment by cuisonghui** [comment] 2021-06-30 08:38
got it! thx. i remove PQScanMultiPassNoPrecomputed.cu and it works
