### ISSUE TITLE
ld: library not found for -lomp

### ISSUE THREAD

**Issue by olalonde** [facebookresearch/faiss#72] opened 2017-04-10 06:36 UTC
On MacOS 10.12.4, I am getting the following:

```
~/code/faiss$  cp example_makefiles/makefile.inc.Mac.brew makefile.inc
~/code/faiss$ make tests/test_blas
/usr/local/opt/llvm/bin/clang++ -fPIC -m64 -Wall -g -O3 -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -I/usr/local/opt/llvm/include -Doverride= tests/test_blas.cpp -o tests/test_blas -framework Accelerate -DFINTEGER=int
ld: library not found for -lomp
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tests/test_blas] Error 1
```

```
/usr/local/opt/llvm/bin/clang++ --version                                                            master
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

**Comment by olalonde** [comment] 2017-04-10 06:48
Managed to compile by adding $(LDFLAGS) to the makefile target but running it gives an error:

```
~/code/faiss$ ./tests/test_blas                               fix-issue-72 ✗
dyld: Library not loaded: @rpath/libomp.dylib
  Referenced from: /Users/olalonde/code/faiss/./tests/test_blas
  Reason: image not found
[1]    32263 abort      ./tests/test_blas
```

**Comment by olalonde** [comment] 2017-04-10 08:54
This seems to magically solve the issue but not sure why

```
install_name_tool -add_rpath /usr/local/opt/llvm/lib tests/demo_ivfpq_indexing
```

```
$ install_name_tool -add_rpath /usr/local/opt/llvm/lib tests/demo_ivfpq_indexing
~/code/faiss$ ./tests/demo_ivfpq_indexing                                       master ✗
[0.000 s] Generating 100000 vectors in 128D for training
[0.197 s] Training the index
Training IVF quantizer on 100000 vectors in 128D
Training IVF residual
  Input training set too big (max size is 65536), sampling 65536 / 100000 vectors
computing residuals
training 4x256 product quantizer on 65536 vectors in 128D
Training PQ slice 0/4
Clustering 65536 points in 32D to 256 clusters, redo 1 times, 25 iterations
  Preprocessing in 0.00 s
  Iteration 24 (0.57 s, search 0.54 s): objective=113241 imbalance=1.004 nsplit=0
Training PQ slice 1/4
Clustering 65536 points in 32D to 256 clusters, redo 1 times, 25 iterations
  Preprocessing in 0.00 s
  Iteration 24 (0.55 s, search 0.52 s): objective=113353 imbalance=1.004 nsplit=0
Training PQ slice 2/4
Clustering 65536 points in 32D to 256 clusters, redo 1 times, 25 iterations
  Preprocessing in 0.00 s
  Iteration 24 (0.55 s, search 0.53 s): objective=113274 imbalance=1.004 nsplit=0
Training PQ slice 3/4
Clustering 65536 points in 32D to 256 clusters, redo 1 times, 25 iterations
  Preprocessing in 0.00 s
Iteration 14 (0.34 s, search 0.32 s): objective=113422 imbalance=1.004 nsplit=0

...
```

**Comment by olalonde** [comment] 2017-04-10 09:09
```
install_name_tool -add_rpath /usr/local/opt/llvm/lib _swigfaiss.so 
```

Also fixed similar error in Python.

**Comment by mdouze** [comment] 2017-04-13 22:00
Hi 

Thanks for posting the solution to the issue, so that people can find it. I am not sure what the problem is/was here. Please close the issue if you consider it fixed.

**Comment by olalonde** [comment] 2017-04-14 15:51
It feels more like a workaround than a real fix but let's close it until someone else can reproduce.

**Comment by madcat1991** [comment] 2017-04-18 08:55
Hi, I had the same problem:

```
$ make tests/test_blas
/usr/local/opt/llvm/bin/clang++ -fPIC -m64 -Wall -g -O3 -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -I/usr/local/opt/llvm/include -Doverride= tests/test_blas.cpp -o tests/test_blas -framework Accelerate -DFINTEGER=int
ld: library not found for -lomp
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tests/test_blas] Error 1
```

As @olalonde mentioned, adding the $(LDFLAGS) to the target solves the problem:
```
tests/test_blas: tests/test_blas.cpp
     $(CC) $(LDFLAGS) $(CFLAGS) $< -o $@ $(BLASLDFLAGS) $(BLASCFLAGS)
```

However, I didn't get errors after that.

The version of OS:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195
```
Used makefile for `brew`.

**Comment by kabom1010** [comment] 2017-06-13 06:12
Hi,  I also had the same problem(install llvm via brew)
it could not find the libomp under /usr/local/lib.
```
cd /usr/local/lib
ln -s /usr/local/Cellar/llvm/3.9.1_1/lib/libomp.dylib libomp.dylib
```

**Comment by mdouze** [comment] 2017-09-04 05:04
Closing.

**Closed by mdouze** 2017-09-04 05:04 UTC
Labels: cant-repro
