### ISSUE TITLE
Segfault when reconstructing non-existing id

### ISSUE THREAD

**Issue by mdouze** [facebookresearch/faiss#686] opened 2019-01-07 12:21 UTC
> You could catch the exception then.
> There is no other function to check if an id exists.

@mdouze when I reconstruct from a id not existing in the index, it gives me "Segmentation fault", which leads to python interpreter crash and cannot be caught. I am using 1.4 version from conda. Any workaround to check if an id exists? Thanks.

_Originally posted by @mylyu in https://github.com/facebookresearch/faiss/issues/439#issuecomment-451914888_

**Comment by mdouze** [comment] 2019-01-07 12:22
@mylyu could you post a short reproduction script?

**Comment by mylyu** [comment] 2019-01-07 14:48
> @mylyu could you post a short reproduction script?

@mdouze Here is one. Sometimes it gives "Segmentation fault", sometimes 
"python: InvertedLists.cpp:56: virtual const uint8_t* faiss::InvertedLists::get_single_code(size_t, size_t) const: Assertion `offset < list_size (list_no)' failed.
Aborted". Neither can be caught.

[reconUnknownIds.zip](https://github.com/facebookresearch/faiss/files/2733135/reconUnknownIds.zip)

**Comment by Enet4** [comment] 2019-01-07 16:51
I can reproduce the problem on this side.

Line 40 is expected to fail, because the given key is outside the limits of the index, which is checked internally by `assert`. I guess that making this a recoverable error rather than a hard assertion would be preferable.

```python
    print(index.reconstruct(100001))
```

A more serious problem occurs in the following instruction (line 49), where a key of greater magnitude is passed to `reconstruct`. Even though the key is an integer and theoretically fits in a `idx_t`, the program crashes.

```python
    print(index.reconstruct(999100001))
```

**Comment by mdouze** [comment] 2019-01-08 18:54
Fixed in internal FB version. Will be included in the next Faiss release.
Diff here:
https://gist.github.com/mdouze/ad61c0f345c75303ca1f032550279ace

**Closed** 2019-02-14 10:06 UTC
Labels: bug
