### ISSUE TITLE
remove is not supported for the GPU？

### ISSUE THREAD

**Issue by AmierCheng** [facebookresearch/faiss#834] opened 2019-05-23 06:52 UTC
remove is not supported for the GPU，When is the remove id operation for GPU?

**Comment by AmierCheng** [comment] 2019-05-23 06:54
I want to remove id from gup, how can I do it?  Thanks.

**Comment by beauby** [comment] 2019-05-23 14:15
Duplicate of #245, closing.

**Closed by beauby** 2019-05-23 14:15 UTC
Labels: question
