### ISSUE TITLE
CUDA error 77

### ISSUE THREAD

**Issue by slh0302** [facebookresearch/faiss#250] opened 2017-11-12 15:53 UTC
When using `Read_Index` (C++) to read the gpu index which saved before, I got this error.
> Faiss assertion 'err__ == cudaSuccess' failed in faiss::gpu::DeviceTensor<T, Dim, Contig, IndexT, > PtrTraits>::~DeviceTensor() [with T = float; int Dim = 3; bool Contig = true; IndexT = int; PtrTraits = faiss::gpu::traits::DefaultPtrTraits] at impl/../utils/DeviceTensor-inl.cuh:61; details: CUDA error 77

I use this code to create `GpuIndexIVFPQ`
```c++
faiss::gpu::StandardGpuResources resources;
faiss::gpu::GpuIndexIVFPQConfig config;
config.device = 9;
config.usePrecomputedTables = false;
faiss::gpu::GpuIndexIVFPQ index (
            &resources, d,
            ncentroids, 32, 8,
            faiss::METRIC_L2,config);
index.verbose = true;
```

and then save index like this
```c++
{ // I/O demo
       const char *outfilename = "/tmp/index_108w_car.faissindex";
       faiss::Index * cpu_index = faiss::gpu::index_gpu_to_cpu (&index);
       write_index (cpu_index, outfilename);
       delete cpu_index;
}
```

finally， I read the index:
```c++
faiss::gpu::GpuClonerOptions* options = new faiss::gpu::GpuClonerOptions();
options->indicesOptions=faiss::gpu::INDICES_64_BIT;
options->useFloat16CoarseQuantizer = false;
options->useFloat16 = false;
options->usePrecomputed = false;
options->reserveVecs = 0;
options->storeTransposed = false;
options->verbose = true;
faiss::gpu::StandardGpuResources resources;
faiss::Index* cpu_index = faiss::read_index(FileName, false);
faiss::gpu::GpuIndexIVFPQ* index = dynamic_cast<faiss::gpu::GpuIndexIVFPQ*>(
                          faiss::gpu::index_cpu_to_gpu(&resources,0 ,cpu_index, options));
```

the GPU device I use is `Tesla K80`, which memory size is 12GB, and I use the `cuda-8.0`

**Comment by slh0302** [comment] 2017-11-12 16:08
Some supplements i got when debugging the program
The error happened when calling this function
```c++
index_->setPrecomputedCodes(ivfpqConfig_.usePrecomputedTables);
```
In this function: line 6 trigger the breakpoint.
```c++
1. IVFPQ::setPrecomputedCodes(bool enable) {
2.   if (precomputedCodes_ != enable) {
3.     precomputedCodes_ = enable;
4. 
5.     if (precomputedCodes_) {
6.       precomputeCodes_();
7.     } else {
8. ...
```

**Comment by wickedfoo** [comment] 2017-11-13 06:53
`config.device = 9;`

You have 10 or more GPUs in the system that you are running?

Also, is the first StandardGpuResources in scope when you instantiate the second one?

**Comment by slh0302** [comment] 2017-11-13 10:03
Yes, I have 16 GPUs at all. But I only use one of them. Typically, in  this code I use is number 9 (I tried other GPUs, like 0, or else).
No, I split the `write_index ` and  `read_index` into two different cpp files which means different StandardGpuResources. 
In the second one, as you can see, I use number 0 GPU：
```c++
faiss::gpu::GpuIndexIVFPQ* index = dynamic_cast<faiss::gpu::GpuIndexIVFPQ*>(
                          faiss::gpu::index_cpu_to_gpu(&resources,0 ,cpu_index, options));
```

**Comment by wickedfoo** [comment] 2017-11-13 19:03
Is the StandardGpuResources remaining in scope while you are doing your work?

**Comment by slh0302** [comment] 2017-11-14 02:08
Yes.

**Comment by wickedfoo** [comment] 2017-11-14 05:10
How much global memory do your GPUs have?

Try disabling precomputed codes and see if you get the issue. Maybe precomputed codes are demanding too much memory.

In the example above, you are setting it to false, but the breakpoint you are hitting has it as true?

**Comment by slh0302** [comment] 2017-11-14 06:53
Each GPU has 12GB memory.
Yes, it's true, even though I set the `precomputed  ` to false. And I found that `precomputedCodes_ ` is false, `enable` is true,  It seems like `precomputed ` is always executed by default.
```c++
2.   if (precomputedCodes_ != enable) {
3.       precomputedCodes_ = enable;
```

**Comment by wickedfoo** [comment] 2017-11-14 15:42
`enable` is true because this is being set to true somewhere:

https://github.com/facebookresearch/faiss/blob/master/gpu/GpuIndexIVFPQ.h#L36

Can you find out where?

What size is the dataset that you are putting into the index (number of vectors x dimensions) and nlist for the index? If this is very large, then precomputed codes will require the allocation of many GB of data for its use, and unfortunately there is nothing in the precomputed code path at the moment that checks for having enough memory to use it.

**Comment by slh0302** [comment] 2017-11-15 11:38
My dataset has about 1 million data (totally, 1,100,000), which dimension is 1024. Yes, I think it's also the question of the `precomputed codes`.
As the variable `enable`, the program run as blew:

First in `main.cpp`:
```c++
faiss::gpu::GpuIndexIVFPQ* index = dynamic_cast<faiss::gpu::GpuIndexIVFPQ*>(
                          faiss::gpu::index_cpu_to_gpu(&resources,0 ,cpu_index, options));
```
then goto `GpuAutoTune.cpp:185`, In `index_cpu_to_gpu` function, call the `return cl.clone_Index(index);`

then came the `GpuAutoTune.cpp:163`:
```c++
148   } else if(auto ipq = dynamic_cast<const faiss::IndexIVFPQ *>(index)) {
      // this `index` is just `cpu_index` as in `main.cpp`
149              if(verbose)
...
155   GpuIndexIVFPQConfig config;
156   config.device = device;
157   config.indicesOptions = indicesOptions;
158   config.flatConfig.useFloat16 = useFloat16CoarseQuantizer;
159   config.flatConfig.storeTransposed = storeTransposed;
160   config.useFloat16LookupTables = useFloat16;
161   config.usePrecomputedTables = usePrecomputed;
      // now the `usePrecomputed` is false,
      // because I set `options` in main.cpp which `precomputed` is false,
162
163   GpuIndexIVFPQ *res = new GpuIndexIVFPQ(resources, ipq, config);
```
this `config` passed in initialization of `GpuIndexIVFPQ` was set as you can see above.

Then goto `GpuIndexIVFPQ.cu:42`
```c++
33   ivfpqConfig_(config),  // this will be use when calling copyFrom()
...
42   copyFrom(index);  // this `index` is equal to `ipq` passed in `GpuAutoTune.cpp:163`
```
After some initialization, came to `GpuIndexIVFPQ.cu:123`
```c++
79  void // function begin at line 79.
80    GpuIndexIVFPQ::copyFrom(const faiss::IndexIVFPQ* index) {
81  DeviceScope scope(device_);
...
86  GpuIndexIVF::copyFrom(index);
    // This index was passed in main.cpp, `index_cpu_to_gpu`,
    // I don't konw whether it's modified along the calling
...
95  // We only support this
96  FAISS_ASSERT(index->pq.byte_per_idx == 1);
97  FAISS_ASSERT(index->by_residual);
98  FAISS_ASSERT(index->polysemous_ht == 0);
99  ivfpqConfig_.usePrecomputedTables = (bool) index->use_precomputed_table;
    // this line the `usePrecomputedTables` was set to be True
...
123 index_->setPrecomputedCodes(ivfpqConfig_.usePrecomputedTables);
```
So as I analyzed above, it's the `cpu_index` which set `usePrecomputedTables`

and this happened in `static IndexIVFPQ *read_ivfpq (FILE *f, uint32_t h, bool try_mmap)` in `index_io.cpp:475`
```c++
493  ivpq->use_precomputed_table = 0;

```
Now, I was very confused about that. because it's set to false, but in `GpuIndexIVFPQ.cu:99`, it's true?

**Comment by mdouze** [comment] 2017-11-17 10:45
Hi 
This seems to be a bug in the cloning code. As a workaround, you can just remove these precomputed tables on the CPU side by setting
```
index-> use_precomputed_table = 0; 
```
on the CPU index before copying it to GPU.

**Comment by zengzh** [comment] 2017-11-18 07:40
Hi,

I tried to reproduce the experimental results on SIFT1B dataset. The script is from the benchs directory and the parameters are as follows:

     ` python bench_gpu_1bn.py  SIFT1M IVF4096,PQ16 -nnn 10`

Adding the '-noptables' to disable precomputed tables didn't help to solve the problem.

**Comment by slh0302** [comment] 2017-11-18 09:13
@mdouze  OK, I will try later.  Expect to fix this.

**Comment by mdouze** [comment] 2017-11-22 13:13
Should be fixed in latest version.

**Closed by mdouze** 2017-11-22 13:13 UTC
Labels: bug
