### ISSUE TITLE
remove_ids from GPU index

### ISSUE THREAD

**Issue by FlYWMe** [facebookresearch/faiss#408] opened 2018-04-16 04:14 UTC
Hi,
I  have some problem when I try to remove_ids ,my index type is "IDMap,Flat".

# Platform

OS: Ubuntu14.04 (16CPUs)

Running on :GPU

GPU memory: 12G

# Reproduction instructions

```
    std::shared_ptr<faiss::Index> faissIndex = nullptr;
    faissIndex.reset(faiss::index_factory(512, "IDMap,Flat", METRIC_L2));
    vector<faiss::gpu::GpuResources *> res;
    vector<int> devs;
    faiss::gpu::GpuMultipleClonerOptions *options = new faiss::gpu::GpuMultipleClonerOptions();
    int ngpus = faiss::gpu::getNumDevices();   // actually, ngpus = 1
    for (int i = 0; i < ngpus; i++)
    {
        res.push_back(new faiss::gpu::StandardGpuResources);
        devs.push_back(i);
    }
    options->indicesOptions = faiss::gpu::INDICES_64_BIT;
    options->useFloat16CoarseQuantizer = false;
    options->useFloat16 = false;
    options->usePrecomputed = false;
    options->reserveVecs = 0;
    options->storeTransposed = false;
    options->verbose = true;
    faissIndex.reset(faiss::gpu::index_gpu_to_cpu(faissIndex.get()));  // convert gpu index to cpu
    faissIndex->remove_ids(sel);  //  here exit a parameter (faiss::IDSelector &sel)
    faissIndex.reset( faiss::gpu::index_cpu_to_gpu_multiple(res, devs, faissIndex.get(), options));

```
When I run this, Take up a lot of memory GPU memory , the program finally core dumped :(
And, the time used very long, much more than add/search.
Thanks.

**Comment by FlYWMe** [comment] 2018-04-16 04:50
This program as a service, I need to call the remove_ids interface multiple times.

**Comment by myl2821** [comment] 2018-04-16 05:03
I think your problem is duplicate of #245

**Comment by mdouze** [comment] 2018-05-11 13:28
remove_ids is not supported on GPU indices
duplicate of #245

**Closed by mdouze** 2018-05-11 13:28 UTC
Labels: GPU, duplicate

**Comment by AmierCheng** [comment] 2019-05-23 06:26
**When is the gpu remove id operation?**

**Comment by AmierCheng** [comment] 2019-05-23 06:26
When is the gpu remove id operation? @mdouze

**Comment by beauby** [comment] 2019-05-23 14:13
@AmierCheng It is not currently on our roadmap AFAIK.
