### ISSUE TITLE
cuda-11 Faiss assertion 'err__ == cudaSuccess'

### ISSUE THREAD

**Issue by paryang** [facebookresearch/faiss#1409] opened 2020-09-15 02:21 UTC
when called faiss::gpu::index_cpu_to_gpu, gives a cuda error,: 
error message: 
IndexIVFPQ size 1000 -> GpuIndexIVFPQ indicesOptions=3 usePrecomputed=0 useFloat16=0 reserveVecs=0
Faiss assertion 'err__ == cudaSuccess' failed in bool faiss::gpu::DeviceVector<T>::append(const T*, size_t, cudaStream_t, bool) [with T = char; size_t = long unsigned int; cudaStream_t = CUstream_st*] at /root/faiss-ori/include/faiss/gpu/utils/DeviceVector.cuh:86; details: CUDA error 1 invalid argument.

# Platform
OS: <Centos 7>
Faiss version: <1.6.3>
gcc version: <5.4.0>
cuda version: <11.0>
Device : Nvidia Telsa T4

Running on:
- [ ] CPU
- [* ] GPU

Interface: 
- [* ] C++
- [ ] Python

# Reproduction instructions

   faiss::Index* cpu_index = faiss::read_index(index_file.c_str(), 0);
    cpu_index->add(nb,baseVecs .data());

    faiss::gpu::StandardGpuResources* res = new faiss::gpu::StandardGpuResources();
    faiss::gpu::GpuClonerOptions* options = new faiss::gpu::GpuClonerOptions();

    options->indicesOptions=faiss::gpu::INDICES_64_BIT;
    options->useFloat16CoarseQuantizer = false;
    options->useFloat16 = false;
    options->usePrecomputed = false;
    options->reserveVecs = 0;
    options->storeTransposed = false;
    options->verbose = true;

    faiss::Index* gpu_index = faiss::gpu::index_cpu_to_gpu(res, 0, cpu_index, options);

ps: for ubuntu 16.04 with Tesla T4, cuda 11, gcc 5.4.0,  the same code works fine.

**Comment by mdouze** [comment] 2020-09-16 07:59
Could be a duplicate of #1405

**Comment by mdouze** [comment] 2020-10-07 06:38
No activity, closing.

**Closed by mdouze** 2020-10-07 06:38 UTC
Labels: GPU, duplicate

**Comment by Aurevoir-68** [comment] 2022-03-07 09:58
> Could be a duplicate of #1405

@mdouze @paryang   Hello, now the problem has been solved. The reason is that cuda11 has new changes. The specific operations are as follows：

gpu/utils/DeviceUtils.cu +114:
else if(att.memoryType == cudaMemoryTypeHost || att.type == 0){
    rerturn -1;
}

**Comment by Aurevoir-68** [comment] 2022-03-07 09:59
> Could be a duplicate of #1405

@mdouze @paryang   Hello, now the problem has been solved. The reason is that cuda11 has new changes. The specific operations are as follows：
```
gpu/utils/DeviceUtils.cu +114:
else if(att.memoryType == cudaMemoryTypeHost || att.type == 0){
    rerturn -1;
}
```

**Comment by Code-Breaker-101** [comment] 2022-05-19 14:19
> > Could be a duplicate of #1405
> 
> @mdouze @paryang Hello, now the problem has been solved. The reason is that cuda11 has new changes. The specific operations are as follows：
> 
> ```
> gpu/utils/DeviceUtils.cu +114:
> else if(att.memoryType == cudaMemoryTypeHost || att.type == 0){
>     rerturn -1;
> }
> ```

Could you tell me in detail how to fix this problem？
