### ISSUE TITLE
Does Faiss distance function support cosine distance? 

### ISSUE THREAD

**Issue by Qiaogx** [facebookresearch/faiss#593] opened 2018-09-18 17:59 UTC
Currently, I see faiss support L2 distance and inner product distance. My question is whether faiss distance function support cosine distance. 

Thanks.
Gary
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

**Comment by Enet4** [comment] 2018-09-18 18:15
This seems like a duplicate of #95. The cosine distance is obtained with the inner product after normalizing all vectors to unit norm.

**Comment by Qiaogx** [comment] 2018-09-18 18:26
Thanks Eduardo!

Does that mean if I want to use cosine similarity, I need to convert both the query vectors and the centroids vectors to unit vector beforehand?

**Comment by Qiaogx** [comment] 2018-09-18 18:43
Thanks for your quick reply. And I will try to add cosine distance option to faiss, since sometimes the input vectors are not unit vectors and converting them beforehand on CPU cost more time.

**Comment by mdouze** [comment] 2018-09-18 20:01
@Qiaogx please don't spend effort on that. Anything you can do will be more expensive than normalizing the vectors.

**Comment by Qiaogx** [comment] 2018-09-18 21:02
Hi Matthijs, 

When using cosine similarity, except normalizing the query and centroid vectors, are there any other factors I need to pay attention to?  I normalized the vectors and set  l2Distance_  to False in faiss/gpu/impl/FlatIndex.cu, but It did not work. 

Thanks.

**Comment by liqima** [comment] 2018-09-22 12:42
> Hi Matthijs,
> 
> When using cosine similarity, except normalizing the query and centroid vectors, are there any other factors I need to pay attention to? I normalized the vectors and set l2Distance_ to False in faiss/gpu/impl/FlatIndex.cu, but It did not work.
> 
> Thanks.

this works.
```
quantizer = faiss.IndexFlatIP(d)
index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_INNER_PRODUCT)
```

**Comment by Qiaogx** [comment] 2018-09-28 17:35
Thank you@liqima. However, it seems IndexIVFPQ does not fully support inner product.

**Comment by mdouze** [comment] 2018-10-01 05:45
Inner product con IndexIVFPQ is fully supported on CPU, otherwise it is a bug. 
Another note: for normalized vectors, L2 and inner product search are equivalent so you can use L2 search.

**Comment by mdouze** [comment] 2018-10-23 04:58
No activity. Closing.

**Closed by mdouze** 2018-10-23 04:58 UTC
Labels: duplicate

**Comment by lmzSDN** [comment] 2019-06-24 07:16
Hi,@Qiaogx,can you tell me how do you achieve the cosine distance?  normalized vector or other ways?

**Comment by mdouze** [comment] 2019-06-24 18:13
Note that there is now a FAQ entry for this question: 
https://github.com/facebookresearch/faiss/wiki/FAQ#how-can-i-index-vectors-for-cosine-distance

**Comment by gabrer** [comment] 2020-06-17 08:20
> Note that there is now a FAQ entry for this question:
> https://github.com/facebookresearch/faiss/wiki/FAQ#how-can-i-index-vectors-for-cosine-distance

Am I the only one having problems in visualizing this FAQ?
I can't see it

**Comment by mdouze** [comment] 2020-06-17 08:44
Thanks! updated the link above to avoid confusion.
