### ISSUE TITLE
ERROR "/bin/sh: ./configure: No such file or directory" When build docker image

### ISSUE THREAD

**Issue by hoangtrungchinh** [facebookresearch/faiss#1612] opened 2021-01-09 11:16 UTC
I have follow this [tutorial](https://github.com/facebookresearch/faiss/blob/master/INSTALL.md) to build faiss Docker Image. When I run `nvidia-docker build -t faiss github.com/facebookresearch/faiss`, It failed.

> Sending build context to Docker daemon  21.23MB
> Step 1/17 : FROM nvidia/cuda:8.0-devel-centos7
>  ---> 22580dbe5fb0
> Step 2/17 : RUN yum-config-manager --add-repo https://yum.repos.intel.com/mkl/setup/intel-mkl.repo
>  ---> Using cache
>  ---> ac90495f6174
> Step 3/17 : RUN rpm --import https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
>  ---> Using cache
>  ---> 216966744812
> Step 4/17 : RUN yum install -y intel-mkl-2019.3-062
>  ---> Using cache
>  ---> 806fb93c2f2e
> Step 5/17 : ENV LD_LIBRARY_PATH /opt/intel/mkl/lib/intel64:$LD_LIBRARY_PATH
>  ---> Using cache
>  ---> 35db9e54534a
> Step 6/17 : ENV LIBRARY_PATH /opt/intel/mkl/lib/intel64:$LIBRARY_PATH
>  ---> Using cache
>  ---> acfe2c7b3464
> Step 7/17 : ENV LD_PRELOAD /usr/lib64/libgomp.so.1:/opt/intel/mkl/lib/intel64/libmkl_def.so:/opt/intel/mkl/lib/intel64/libmkl_avx2.so:/opt/intel/mkl/lib/intel64/libmkl_core.so:/opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so:/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
>  ---> Using cache
>  ---> 4a33cef311ce
> Step 8/17 : RUN yum install -y gcc-c++ make swig3
>  ---> Using cache
>  ---> dce15e481b8b
> Step 9/17 : RUN yum install -y python-devel numpy
>  ---> Using cache
>  ---> 5d038f9bcd95
> Step 10/17 : COPY . /opt/faiss
>  ---> f08a9c5622e1
> Step 11/17 : WORKDIR /opt/faiss
>  ---> Running in 1619d3ba9496
> Removing intermediate container 1619d3ba9496
>  ---> 45c4f1cfaff1
> Step 12/17 : RUN ./configure --prefix=/usr --libdir=/usr/lib64 --without-cuda
>  ---> Running in 55711efa61a0
> /bin/sh: ./configure: No such file or directory
> The command '/bin/sh -c ./configure --prefix=/usr --libdir=/usr/lib64 --without-cuda' returned a non-zero code: 127

How can I fix it?

**Comment by Enet4** [comment] 2021-01-09 16:34
This is likely a duplicate of #1584. Dockerfile has been outdated for a while.

**Closed** 2021-01-10 02:23 UTC
