### ISSUE TITLE
IndexFlatL2 calculations are wrong

### ISSUE THREAD

**Issue by onurtore** [facebookresearch/faiss#3245] opened 2024-02-07 14:04 UTC
Hello,

I have been testing the IndexFlatL2 with GPS coordinates and results are weird.

My query vector is:

array([[4208848. , 2334863.5, 4171170.2]], dtype=float32)

What Faiss returns me as closest 

array([[4208292. , 2335623.5, 4171305. ]], dtype=float32)

But I now for a fact that, this vector exitsts in the index

array([[4208843.5, 2334869.5, 4171171.5]], dtype=float32)

The L2 distance to the vector that faiss return is 951.2589, however the distance to the vector I need is 7.603453.

so I do not understand, my vectors are all in float32, I am doing only one query search, and I even tried to normalize using faiss.normalize_L2 function. However results are still wrong.

**Comment by mdouze** [comment] 2024-02-13 13:05
This is almost certainly related to accuracy loss with float32, see 

https://github.com/facebookresearch/faiss/wiki/FAQ#why-do-i-get-weird-results-with-brute-force-search-on-vectors-with-large-components

NB that Faiss is not very appropriate for indexing low-dimensional vectors like 3D data.

**Comment by kno10** [comment] 2024-03-22 08:38
This very likely is an instance of this problem, and a duplicate of #297 (and many more)

The equation used by FAISS, $||a||^2+||b||^2-2ab$, while algebraically equivalent to $(a-b)^2$, is numerically highly problematic whenever the vector norms are similar in value to the dot products (i.e., the vectors point into the same direction).

The FAQ claims "A workaround is to center the vector components", but that certainly will not solve everything. Make all your data points orthogonal, then you will be fine. ;-)

The workaround employed by sklearn is to upcast to double precision, this gives decent results if your input is floats, but of course is more costly. For double precision, Euclidean distances in sklearn have a similar issue!

Do not use FAISS if you need high accuracy data analysis (see also a similar issue within FAISS PCA, #773 ). But the accuracy loss for small distances may be *acceptable* if you use this, e.g., to choose cluster centers for product quantization. To identify the nearest cluster center, you will often not need high accuracy in the distance computation (when the clusters are well spread out), but for acutal kNN search - or worse, radius search - where you are interested in really small distances, I would recommend a more accurate computation.

**Comment by onurtore** [comment] 2024-03-24 15:19
> This very likely is an instance of this problem, and a duplicate of #297 (and many more)
> 
> The equation used by FAISS, ||a||2+||b||2−2ab, while algebraically equivalent to (a−b)2, is numerically highly problematic whenever the vector norms are similar in value to the dot products (i.e., the vectors point into the same direction).
> 
> The FAQ claims "A workaround is to center the vector components", but that certainly will not solve everything. Make all your data points orthogonal, then you will be fine. ;-)
> 
> The workaround employed by sklearn is to upcast to double precision, this gives decent results if your input is floats, but of course is more costly. For double precision, Euclidean distances in sklearn have a similar issue!
> 
> Do not use FAISS if you need high accuracy data analysis (see also a similar issue within FAISS PCA, #773 ). But the accuracy loss for small distances may be _acceptable_ if you use this, e.g., to choose cluster centers for product quantization. To identify the nearest cluster center, you will often not need high accuracy in the distance computation (when the clusters are well spread out), but for acutal kNN search - or worse, radius search - where you are interested in really small distances, I would recommend a more accurate computation.

What does make all your data points orthogonal mean, and how can I accomplish it?

The easiest work around for us to use CPU rather than GPU which is exact.

**Comment by kno10** [comment] 2024-03-25 08:43
Assume you have finite precision math, for example three decimal digits. Compute the difference between the vectors 1 and 1.001. If you do (a-b)^2=(0.001)^2=0.000001, exact. If you do |a|²+|b|²-2ab=(1.0)^2+(1.001)^2-2*(1.0*1.001)= (in finite precision) = 1.0+1.0-2*(1.0) = 0. To have the proper result with this equation, you need to be able to store the interim results with sufficient precision, i.e. 2.000001 here. So you may need double the resolution in the intermediate steps.
That is why upcasting the data to double precision float reduces this problem.

As for making them all orthogonal, that is equal to saying make them all maximally distant. That was not meant to be a real solution, but rather mathematically: for orthogonal vectors 2<a,b>=0 the last term is 0, and hence the problem is resolved. This shows that the problem is large whenever the dot product is large, i.e., when the vectors are similar.

**Comment by mdouze** [comment] 2024-03-26 08:50
Thanks for the explanation @kno10 
Nb that in ML workloads, it is more and more common to use low precision floating point representations (float32 -> float16 and currently people are looking into 8-bit variants). This is because the complexity of hardware implementations of scalar multiplication is quadratic in the size of the mantissa. Therefore, to benefit from the speedups, developers are willing to carefully manage the conditioning of their data. 
Therefore, we often trade precision for speed in Faiss.

**Comment by kno10** [comment] 2024-03-26 09:23
The thing is that this computation causes much more loss than caused by the data type. You don't get "single precision" accuracy, but you get as little as zero accuracy because of catastrophic cancellation. The standard equation is what gives you single precision.

Both CPUs and GPUs often use higher precision registers for intermediate results, for example FMA operations on Intel CPUs often use an 80-bit float internally for the computation, only the result is then reduced to the desired size.
At least the first generation of Nvidia tensor cores used 16 bit input with 32 bit computation and accumulators to be better able at retaining the full input precision.
https://developer.nvidia.com/blog/programming-tensor-cores-cuda-9/

**Comment by onurtore** [comment] 2024-03-26 10:57
@kno10 , @mdouze  thank you both for the explanation.

**Closed** 2024-03-26 10:57 UTC
Labels: question
