### ISSUE TITLE
IDSelector Not Working on GPU in Faiss 1.8.0 with Search Parameters

### ISSUE THREAD

**Issue by Tottowich** [facebookresearch/faiss#3924] opened 2024-10-08 10:06 UTC
### **Summary**

Can't get `IDSelector` to work on GPU, though it works on CPU. The expected behavior (returning -1 for unselected items) does not occur on GPU when using `SearchParameters`, see MWE below. Is this feature not implemented on GPU? It says [here]() that  GpuIndexFlatL2 may be used as a drop-in replacement while in the [pytorch-test](https://github.com/facebookresearch/faiss/blob/main/faiss/gpu/test/torch_test_contrib_gpu.py) it says that 
```python
    # tests range_search
    def test_range_search(self):
        # This is not currently implemented on GPU indices
        return
```

### **Platform**

OS: Ubuntu 22.04  
CUDA Version: 11.8

Faiss version (tested with both):

- Installed via:
  ```bash
  conda install -c pytorch -c nvidia faiss-gpu=1.8.0
  ```
  Results: Issue persists, no filtering behavior on GPU.

- Installed via:
  ```bash
  conda install -c pytorch -c nvidia -c rapidsai -c conda-forge faiss-gpu-raft=1.8.0
  ```
  Results: Same issue, no difference in behavior.

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

---

### **Reproduction instructions**

```python
import numpy as np
import faiss

# Set parameters
d = 32  # Dimension of the data (vector length)
nlist = 100  # Number of cluster centers
num_users = 1_000
num_items = 65_536
k = 32  # Number of nearest neighbors

# Random embeddings
user_embeddings = np.random.random((num_users, d))
item_embeddings = np.random.random((num_items, d))

# Flat index with Inner Product
index = faiss.IndexFlatL2(d)
index.train(item_embeddings)
index.add(item_embeddings)

# GPU resources
res = faiss.StandardGpuResources()
gpu_index = faiss.index_cpu_to_gpu(res, 0, index)

# Create an IDSelector for the subset (empty selection for now)
id_selector = faiss.IDSelectorBitmap(np.zeros(num_items, dtype=np.uint8))

# Define search parameters and apply IDSelector
search_params = faiss.SearchParameters()
search_params.sel = id_selector

# Perform searches without search parameters (on CPU and GPU)
dist_cpu_no_params, ind_cpu_no_params = index.search(user_embeddings, k)
dist_gpu_no_params, ind_gpu_no_params = gpu_index.search(user_embeddings, k)

# Perform searches with search parameters (on CPU and GPU)
dist_cpu, ind_cpu = index.search(user_embeddings, k, params=search_params)
dist_gpu, ind_gpu = gpu_index.search(user_embeddings, k, params=search_params)

# Display results
ex_to_show = 5  # Show only first 5 results
k_to_show = 5   # Show top 5 neighbors

print(f"CPU search (no params): indices = {ind_cpu_no_params[:ex_to_show, :k_to_show]}")
print(f"GPU search (no params): indices = {ind_gpu_no_params[:ex_to_show, :k_to_show]}")
print(f"CPU search (with params): indices = {ind_cpu[:ex_to_show, :k_to_show]}")
print(f"GPU search (with params): indices = {ind_gpu[:ex_to_show, :k_to_show]}")
```

### **Expected Output:**

- **CPU (with `search_params`)**: `[-1 -1 -1 -1 -1]` indicating that no items were selected.
- **GPU (with `search_params`)**: Expected the same output as CPU but instead returns normal indices (i.e., selection filter is ignored).

### **Actual Output:**

```
CPU search (no params): indices = [[64920 51746  1300 33010 62139]
                                   [49768 39212 62139 35448 55487]
                                   [50140 49768 37837 55487 39386]
                                   [31043 35448 45516 50140 25945]
                                   [33010 37150 55487  1676 55744]]
GPU search (no params): indices = [[64920 51746  1300 33010 62139]
                                   [49768 39212 62139 35448 55487]
                                   [50140 49768 37837 55487 39386]
                                   [31043 35448 45516 50140 25945]
                                   [33010 37150 55487  1676 55744]]
CPU search (with params): indices = [[-1 -1 -1 -1 -1]
                                     [-1 -1 -1 -1 -1]
                                     [-1 -1 -1 -1 -1]
                                     [-1 -1 -1 -1 -1]
                                     [-1 -1 -1 -1 -1]]
GPU search (with params): indices = [[64920 51746  1300 33010 62139]
                                     [49768 39212 62139 35448 55487]
                                     [50140 49768 37837 55487 39386]
                                     [31043 35448 45516 50140 25945]
                                     [33010 37150 55487  1676 55744]]
```

### **Issue:**

- **CPU**: `IDSelector` works as expected, returning `-1` for unselected items.
- **GPU**: `IDSelector` is ignored. It returns regular indices, even when `search_params` are applied, indicating the filter is not functioning on the GPU.

---

### **Steps Tried:**

- Tested on two different Faiss GPU installations (`faiss-gpu=1.8.0` and `faiss-gpu-raft=1.8.0`).
- Issue persists across both versions.

**Comment by asadoughi** [comment] 2024-10-08 22:40
Hi @Tottowich thanks for your feature request. I am closing this as its a duplicate of #3114. It is correct that IDSelector-based filtering is not currently supported on the GPU implementation.

**Closed by asadoughi** 2024-10-08 22:40 UTC
Labels: GPU
